# Generated by Django 4.1.6 on 2023-02-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caidalibre',
            old_name='distanica',
            new_name='distancia',
        ),
    ]
