# Generated by Django 4.1.6 on 2023-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_distanica_caidalibre_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caidalibre',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='idCL'),
        ),
    ]
