# Generated by Django 4.1.6 on 2023-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_caidalibre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caidalibre',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='caidalibre',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='caidalibre',
            name='inp',
            field=models.IntegerField(null=True, verbose_name='inp'),
        ),
        migrations.AddField(
            model_name='caidalibre',
            name='ou',
            field=models.IntegerField(null=True, verbose_name='ou'),
        ),
        migrations.AlterField(
            model_name='caidalibre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
